#!/bin/bash

# Run your build commands here
php artisan down
composer install --no-dev --optimize-autoloader
php artisan migrate --force

source ~/.nvm/nvm.sh

# Refresh node modules
nvm install
wait
yarn
yarn build

php artisan up