# Settings for Linguist language program detection.

# Arbitrary increases for commercially private repos.
additions:
  PHP: 3000000
  Ruby: 4204694
  JavaScript: 611638

# Arbitrary adjustments to account for frameworks and libraries
# (Lower number means subtracting more, i.e. 0.4 = keep 40% of total code)
subtractions:
  Ruby: 0.5 # Account for code I didn't write
  JavaScript: 0.5 # Every framework contains generated JavaScript code.

# Global ignore
ignore: [
  'Markdown', 
  'ASP.NET',
  'MDX',
  'Dockerfile',
  'Elixir',
  'HTML',
  'CSS',
  'SCSS',
  'Blade',
  'ASL',
  'CoffeeScript',
  'Starlark',
]